
fastlane_version "2.26.1"

default_platform :ios

platform :ios do

  desc "Bootstrap dependencies"
  lane :bootstrap do
    cocoapods(
      clean: true,
      repo_update: true
    )
  end

  desc "Run unit tests and check library"
  lane :test do
    bootstrap
    scan(workspace: "TeamupKit.xcworkspace", scheme: "TeamupKit", clean: true)
    # pod_lib_lint(verbose: true)
  end

end